title: Bill's Blog
author: bwalker34
email: 44475529+blwalker34@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Website will be used for blogging, for signalling learning progress, and for doscumenting completed projects.

# social links
github_username:  44475529+blwalker34@users.noreply.github.com

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
